name: ON Master Push
on:
  push:
    branches:
      - GHA-testing-fake-master
      - GHA-Testing
      
jobs:
  Terraform_Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - run: npm run deploy
