name: On PR (tf plan) Dummy Workflow
on:
  pull_request:
    types: [opened]
    branches:
      - GHA-testing-fake-master


jobs:
  Terraform_Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
      - run: npm run plan
